# The executable
set(SUB_PROJECT_APP gui_skeleton)

if(APPLE)
	file(GLOB SKELETON_RES ${CMAKE_CURRENT_SOURCE_DIR}/skeleton*.*)
	set_source_files_properties(${SKELETON_RES} PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
    add_executable(${SUB_PROJECT_APP} MACOSX_BUNDLE ../skeleton.c ${SKELETON_RES})
	set(CPACK_BUNDLE_NAME "${SUB_PROJECT_APP}")
	set(CPACK_BUNDLE_PLIST ${CMAKE_CURRENT_SOURCE_DIR}/info.plist)
	set(CPACK_BUNDLE_ICON ${CMAKE_CURRENT_SOURCE_DIR}/skeleton_64x64.png)
	set(MACOSX_BUNDLE_BUNDLE_VERSION ${PROJECT_VERSION})
	set(MACOSX_BUNDLE_COPYRIGHT "© 2026 ${PROJECT_NAME}")
	set(MACOSX_BUNDLE_INFO_STRING ${PROJECT_DESCRIPTION})
else()
	if(WIN32)
		set(CMAKE_WIN32_EXECUTABLE ON)
        add_executable(${SUB_PROJECT_APP} ../skeleton.c
			${CMAKE_CURRENT_SOURCE_DIR}/res.rc)
	else()
    	add_executable(${SUB_PROJECT_APP} ../skeleton.c)
	endif()
endif()
target_link_libraries(${SUB_PROJECT_APP} ${PROJECT_NAME})
target_include_directories(${SUB_PROJECT_APP}
	PRIVATE $<BUILD_INTERFACE:${CMAKE_SOURCE_DIR}/include>)

set_target_properties(${SUB_PROJECT_APP} PROPERTIES
	EXPORT_NAME ${SUB_PROJECT_APP}
    OUTPUT_NAME ${SUB_PROJECT_APP}
	VERSION ${PROJECT_VERSION}
	SOVERSION ${PROJECT_VERSION_MAJOR}
)

if(APPLE)
	install(
		TARGETS ${PROJECT_NAME} ${SUB_PROJECT_APP}
		EXPORT "${PROJECT_NAME}Targets"
		ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
		LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
		RUNTIME DESTINATION BUNDLE DESTINATION ${CMAKE_INSTALL_BINDIR}
		PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
		INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
	)
else()
	install(
		TARGETS ${PROJECT_NAME} ${SUB_PROJECT_APP}
		EXPORT "${PROJECT_NAME}Targets"
		ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
		LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
		RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
		PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
		INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
	)
endif()

install(
	EXPORT "${PROJECT_NAME}Targets"
	FILE "${PROJECT_NAME}Targets.cmake"
	NAMESPACE GUI::
	DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/${PROJECT_NAME}"
)

install(TARGETS ${PROJECT_NAME} DESTINATION lib)
install(TARGETS ${SUB_PROJECT_APP} DESTINATION bin)
install(DIRECTORY include DESTINATION include)
set(CPACK_INSTALL_CMAKE_CONFIGURATIONS Release)
